"""add class_for and subject fields

Revision ID: 248ad8b8d52c
Revises: fe38474cceef
Create Date: 2025-12-05 23:03:50.900305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '248ad8b8d52c'
down_revision: Union[str, Sequence[str], None] = 'fe38474cceef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('class_for', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('subject', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'subject')
    op.drop_column('questions', 'class_for')
    # ### end Alembic commands ###
